import type { Metadata } from 'next';
import './globals.css';
import { Layout } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="m-20">
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
